### ISSUE TITLE
TypeError: '<=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by korthout** [erik/lastcast#14]
I encountered the following problem a couple times, during which lastcast crashed. However, I can no longer reproduce it and the symptom has solved itself. It seems related to issue #6.

```
Traceback (most recent call last):
  File "/usr/local/bin/lastcast", line 11, in <module>
    sys.exit(main())
  File "/Users/nicokorthout/Library/Python/3.6/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nicokorthout/Library/Python/3.6/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/nicokorthout/Library/Python/3.6/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nicokorthout/Library/Python/3.6/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/nicokorthout/Library/Python/3.6/lib/python/site-packages/lastcast/__init__.py", line 213, in main
    ScrobbleListener(config).listen()
  File "/Users/nicokorthout/Library/Python/3.6/lib/python/site-packages/lastcast/__init__.py", line 51, in listen
    self.poll()
  File "/Users/nicokorthout/Library/Python/3.6/lib/python/site-packages/lastcast/__init__.py", line 87, in poll
    if status.current_time <= 0 or status.duration <= 0:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

**Comment by erik** [comment]
Ah, this is because I was only testing against python2.7.

```
➜  ~ python2.7 -c 'print None < 0'
True
➜  ~ python3.6 -c 'print(None < 0)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

Thanks again for reporting! I'll post a fix a bit later. 

If you want to just get it working for the time being, run lastcast with Python 2.7

**Comment by korthout** [comment]
Great! Again very quickly solved and the solution looks elegantly simple. My compliments.
