### ISSUE TITLE
Lastcast stops working

### ISSUE THREAD

**Issue by MisterObvious25** [erik/lastcast#16]
While scrobbling(spotify on chromecast) perfectly sometimes i get this error

Traceback (most recent call last):
  File "/usr/local/bin/lastcast", line 9, in <module>
    load_entry_point('lastcast==0.1.5', 'console_scripts', 'lastcast')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/lastcast/__init__.py", line 213, in main
    ScrobbleListener(config).listen()
  File "/usr/local/lib/python2.7/dist-packages/lastcast/__init__.py", line 51, in listen
    self.poll()
  File "/usr/local/lib/python2.7/dist-packages/lastcast/__init__.py", line 90, in poll
    self._on_status(status)
  File "/usr/local/lib/python2.7/dist-packages/lastcast/__init__.py", line 127, in _on_status
    self._scrobble(meta)
  File "/usr/local/lib/python2.7/dist-packages/lastcast/__init__.py", line 142, in _scrobble
    print(u'Scrobbling: {artist} - {title} [{album}]'.format(**track_meta))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 24: ordinal not in range(128)

It happens when it tries to scrobble this song

**"I Don’t Wanna Live Forever (Fifty Shades Darker) - From "Fifty Shades Darker (Original Motion Picture Soundtrack)" – ZAYN, Taylor Swift"**

and after that the program just stops.

**Comment by erik** [comment]
Thanks for taking the time to report!

I actually recently hit this issue myself, and the solution for me just involved setting the environment variable `PYTHONIOENCODING` correctly.

See if running lastcast like so fixes the issue for you. You should be able to check by listening to that same song again.

```bash
export PYTHONIOENCODING=UTF-8

lastcast
```

**Comment by MisterObvious25** [comment]
Yes thank you very much, this solves it for me.

**Comment by erik** [comment]
Awesome!

I also created PR #17, which should prevent you from needing to set that environment variable in the future.

Thanks again!
