### ISSUE TITLE
Run lastcast in background

### ISSUE THREAD

**Issue by korthout** [erik/lastcast#8]
As described in the README, lastcast is not very resilient yet. Running it as a background process would likely be a first step towards more stable scrobbling.

**Comment by erik** [comment]
This is a good idea and something I had been putting off for a while. I'll work on this one in the next few days 👍

**Comment by korthout** [comment]
Great! You already worked on it a week ago. I had not expected that. Anyways, today I tried out the new version and it seems to work partially. Sleeping my mac for a minute worked fine. It simply logged a message and continued:

```
WARNING:pychromecast.socket_client:Error communicating with socket, resetting connection
```

I can imagine it works in more situations. However, turning off my WiFi induced a crash. 

```
Traceback (most recent call last):
  File "/usr/local/bin/lastcast", line 11, in <module>
    load_entry_point('lastcast==0.1.2', 'console_scripts', 'lastcast')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/lastcast/__init__.py", line 198, in main
    listener = ScrobbleListener(config).listen()
  File "/Library/Python/2.7/site-packages/lastcast/__init__.py", line 44, in listen
    self.poll()
  File "/Library/Python/2.7/site-packages/lastcast/__init__.py", line 81, in poll
    self._on_status(status)
  File "/Library/Python/2.7/site-packages/lastcast/__init__.py", line 109, in _on_status
    self._now_playing(meta)
  File "/Library/Python/2.7/site-packages/lastcast/__init__.py", line 121, in _now_playing
    self.lastfm.update_now_playing(**track_meta)
  File "/Library/Python/2.7/site-packages/pylast/__init__.py", line 754, in update_now_playing
    _Request(self, "track.updateNowPlaying", params).execute()
  File "/Library/Python/2.7/site-packages/pylast/__init__.py", line 1222, in execute
    response = self._download_response()
  File "/Library/Python/2.7/site-packages/pylast/__init__.py", line 1204, in _download_response
    raise NetworkError(self.network, e)
pylast.NetworkError: NetworkError: [Errno 8] nodename nor servname provided, or not known
```
Anyhow, thanks for the improvement.

**Comment by erik** [comment]
Ah nice, seems like you interrupted the connection exactly when it was trying to talk to last.fm. Didn't handle that condition, I'll add another exception handler. 

Thanks again Nico!

**Comment by erik** [comment]
I merged a couple different things that should increase the stability of lastcast going forward. I'm sure there's more that can be done but I'm going to close this ticket for now. Thanks again for reporting issues @korthout!
